/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `t_person` */

insert  into `t_person`(`PERSON_ID`,`PERSONE_ID`,`PERSON_FIRST_NAME`,`PERSON_MIDDLE_NAME`,`PERSON_LAST_NAME`,`PERSON_NICKNAME`,`PERSON_GENDER`,`PERSON_BIRTH_PLACE`,`PERSON_BIRTH_DATE`,`PERSON_EMAIL`,`PERSON_CONTACT`,`PERSON_PARENT`,`PERSON_MAPPING`,`RELATION_ORGANIZATION_ID`,`STRUCTURE_ID`,`DIVISION_ID`,`OFFICE_ID`,`PERSON_IS_DELETED`,`PERSON_CREATED_BY`,`PERSON_CREATED_DATE`,`PERSON_UPDATED_BY`,`PERSON_UPDATED_DATE`,`PERSON_CATEGORY`,`PERSON_HIRE_DATE`,`PERSON_END_DATE`,`PERSON_KTP`,`PERSON_NPWP`,`PERSON_BANK_ACCOUNT_ID`,`PERSON_IMAGE_ID`,`PERSON_KK`,`PERSON_BLOOD_TYPE`,`PERSON_BLOOD_RHESUS`,`PERSON_MARITAL_STATUS`,`TAX_STATUS_ID`,`PERSON_RECRUITMENT_LOCATION`,`PERSON_LOCK_UPDATE`,`PERSON_LOCK_UPDATED_DATE`,`PERSON_SALARY_ADJUSTMENT1`,`PERSON_SALARY_ADJUSTMENT2`) values (1,NULL,'Fadhlan',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','fadhlan@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(2,NULL,'Apep',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','apep@email.com','asdsad',NULL,NULL,1,2,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:36',NULL,NULL,NULL,'asda','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(3,NULL,'Mei',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','mei@email.com','2323',NULL,NULL,1,3,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(4,NULL,'Haris',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','haris@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(5,NULL,'Pian',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','pian@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(6,NULL,'Fitano',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','fitano@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
