/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.2.0 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `r_method_notification` */

insert  into `r_method_notification`(`METHOD_NOTIFICATION_ID`,`METHOD_NOTIFICATION_NAME`,`METHOD_NOTIFICATION_CREATED_BY`,`METHOD_NOTIFICATION_CREATED_DATE`,`METHOD_NOTIFICATION_UPDATED_BY`,`METHOD_NOTIFICATION_UPDATED_DATE`) values (1,'App Notification',1,'2024-10-16 10:39:45',NULL,NULL),(2,'Email',1,'2024-10-16 10:39:45',NULL,NULL),(3,'WhatsApp',1,'2024-10-16 10:39:45',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
