/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `t_company` */

insert  into `t_company`(`COMPANY_ID`,`COMPANY_NAME`,`COMPANY_PARENT_ID`,`COMPANY_ABBREVIATION`,`COMPANY_AKA`,`COMPANY_GROUP`,`COMPANY_CREATED_BY`,`COMPANY_CREATED_DATE`,`COMPANY_UPDATED_BY`,`COMPANY_UPDATED_DATE`,`COMPANY_DESCRIPTION`,`COMPANY_ALIAS`,`COMPANY_EMAIL`,`COMPANY_WEBSITE`,`COMPANY_MAPPING`,`HR_MANAGED_BY_APP`,`IS_TBK`,`COMPANY_LOGO_ID`,`COMPANY_SIGNATURE_NAME`,`COMPANY_SIGNATURE_TITLE`,`COMPANY_BANK_ACCOUNT_NUMBER`,`COMPANY_BANK_ACCOUNT_NAME`,`RELATION_PROFESSION_ID`,`RELATION_LOB_ID`,`PRE_SALUTATION`,`POST_SALUTATION`,`relation_status_id`,`is_deleted`) values (1,'Fresnel Perdana Mandiri',NULL,'FPM','FPM',NULL,NULL,'2024-08-27 11:53:42',NULL,'2024-08-27 11:53:42',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'12345','ASDFG',NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
