/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`phoenix` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `phoenix`;

/*Table structure for table `t_person` */

DROP TABLE IF EXISTS `t_person`;

CREATE TABLE `t_person` (
  `PERSON_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `PERSONE_ID` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_FIRST_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_MIDDLE_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_LAST_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_NICKNAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_GENDER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'm = male, f = female',
  `PERSON_BIRTH_PLACE` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BIRTH_DATE` date DEFAULT NULL,
  `PERSON_EMAIL` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_CONTACT` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_PARENT` bigint unsigned DEFAULT NULL,
  `PERSON_MAPPING` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_ID` bigint unsigned DEFAULT NULL,
  `STRUCTURE_ID` int DEFAULT NULL,
  `DIVISION_ID` int DEFAULT NULL,
  `OFFICE_ID` int DEFAULT NULL,
  `PERSON_IS_DELETED` int DEFAULT NULL COMMENT '0 = ACTIVE, 1=INACTIVE',
  `PERSON_CREATED_BY` bigint DEFAULT NULL,
  `PERSON_CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PERSON_UPDATED_BY` bigint DEFAULT NULL,
  `PERSON_UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PERSON_CATEGORY` int DEFAULT NULL,
  `PERSON_HIRE_DATE` date DEFAULT NULL,
  `PERSON_END_DATE` date DEFAULT NULL,
  `PERSON_KTP` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_NPWP` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BANK_ACCOUNT_ID` int DEFAULT NULL,
  `PERSON_IMAGE_ID` int DEFAULT NULL,
  `PERSON_KK` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BLOOD_TYPE` int DEFAULT NULL COMMENT '1=A, 2=B, 3=AB, 4=0',
  `PERSON_BLOOD_RHESUS` int DEFAULT NULL COMMENT '1=positive, 2=negative',
  `PERSON_MARITAL_STATUS` int DEFAULT NULL COMMENT '1=Single, 2= Married,3=Divorced,4=Widowed',
  `TAX_STATUS_ID` int DEFAULT NULL,
  `PERSON_RECRUITMENT_LOCATION` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_LOCK_UPDATE` int DEFAULT NULL COMMENT 'null/0 = lock 1=unlock',
  `PERSON_LOCK_UPDATED_DATE` date DEFAULT NULL,
  `PERSON_SALARY_ADJUSTMENT1` date DEFAULT NULL,
  `PERSON_SALARY_ADJUSTMENT2` date DEFAULT NULL,
  PRIMARY KEY (`PERSON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `t_person` */

insert  into `t_person`(`PERSON_ID`,`PERSONE_ID`,`PERSON_FIRST_NAME`,`PERSON_MIDDLE_NAME`,`PERSON_LAST_NAME`,`PERSON_NICKNAME`,`PERSON_GENDER`,`PERSON_BIRTH_PLACE`,`PERSON_BIRTH_DATE`,`PERSON_EMAIL`,`PERSON_CONTACT`,`PERSON_PARENT`,`PERSON_MAPPING`,`RELATION_ORGANIZATION_ID`,`STRUCTURE_ID`,`DIVISION_ID`,`OFFICE_ID`,`PERSON_IS_DELETED`,`PERSON_CREATED_BY`,`PERSON_CREATED_DATE`,`PERSON_UPDATED_BY`,`PERSON_UPDATED_DATE`,`PERSON_CATEGORY`,`PERSON_HIRE_DATE`,`PERSON_END_DATE`,`PERSON_KTP`,`PERSON_NPWP`,`PERSON_BANK_ACCOUNT_ID`,`PERSON_IMAGE_ID`,`PERSON_KK`,`PERSON_BLOOD_TYPE`,`PERSON_BLOOD_RHESUS`,`PERSON_MARITAL_STATUS`,`TAX_STATUS_ID`,`PERSON_RECRUITMENT_LOCATION`,`PERSON_LOCK_UPDATE`,`PERSON_LOCK_UPDATED_DATE`,`PERSON_SALARY_ADJUSTMENT1`,`PERSON_SALARY_ADJUSTMENT2`) values (1,NULL,'Fadhlan',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','fadhlan@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(2,NULL,'Apep',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','apep@email.com','asdsad',NULL,NULL,1,2,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:36',NULL,NULL,NULL,'asda','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(3,NULL,'Mei',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','mei@email.com','2323',NULL,NULL,1,3,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(4,NULL,'Haris',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','haris@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(5,NULL,'Pian',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','pian@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(6,NULL,'Fitano',NULL,NULL,NULL,NULL,'Jakarta','2024-08-03','fitano@email.com','2323',NULL,NULL,1,4,1,NULL,NULL,NULL,NULL,1,'2024-08-03 16:12:26',NULL,NULL,NULL,'sadad','sadsad',NULL,NULL,'sadad',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
