/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `t_relation` */

insert  into `t_relation`(`RELATION_ORGANIZATION_ID`,`RELATION_ORGANIZATION_NAME`,`RELATION_ORGANIZATION_PARENT_ID`,`RELATION_ORGANIZATION_ABBREVIATION`,`RELATION_ORGANIZATION_AKA`,`RELATION_ORGANIZATION_GROUP`,`RELATION_ORGANIZATION_CREATED_BY`,`RELATION_ORGANIZATION_CREATED_DATE`,`RELATION_ORGANIZATION_UPDATED_BY`,`RELATION_ORGANIZATION_UPDATED_DATE`,`RELATION_ORGANIZATION_DESCRIPTION`,`RELATION_ORGANIZATION_ALIAS`,`RELATION_ORGANIZATION_EMAIL`,`RELATION_ORGANIZATION_MAPPING`,`HR_MANAGED_BY_APP`,`IS_TBK`,`RELATION_ORGANIZATION_LOGO_ID`,`RELATION_ORGANIZATION_SIGNATURE_NAME`,`RELATION_ORGANIZATION_SIGNATURE_TITLE`,`RELATION_ORGANIZATION_BANK_ACCOUNT_NUMBER`,`RELATION_ORGANIZATION_BANK_ACCOUNT_NAME`,`RELATION_PROFESSION_ID`,`RELATION_LOB_ID`,`PRE_SALUTATION`,`POST_SALUTATION`,`relation_status_id`,`is_deleted`) values (1,'Killian Teknologi Indonesia',0,'KTI',NULL,NULL,'1','2024-07-31 04:33:09',NULL,NULL,NULL,'Killian Teknologi Indonesia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),(2,'Pelabuhan Indonesia',0,'PELINDO',NULL,NULL,'1','2024-07-31 04:33:36',NULL,NULL,NULL,'Pelabuhan Indonesia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),(3,'Sari Enesis Indah',0,'SEI',NULL,NULL,'1','2024-07-31 04:34:05',NULL,NULL,NULL,'Sari Enesis Indah',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),(4,'Fresnel',0,'FPM',NULL,NULL,'1','2024-08-06 04:22:39',NULL,NULL,NULL,'Fresnel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
