/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`phoenix` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `phoenix`;

/*Table structure for table `t_relation` */

DROP TABLE IF EXISTS `t_relation`;

CREATE TABLE `t_relation` (
  `RELATION_ORGANIZATION_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `RELATION_ORGANIZATION_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_PARENT_ID` bigint unsigned DEFAULT NULL,
  `RELATION_ORGANIZATION_ABBREVIATION` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_AKA` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_GROUP` bigint unsigned DEFAULT NULL,
  `RELATION_ORGANIZATION_CREATED_BY` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RELATION_ORGANIZATION_UPDATED_BY` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RELATION_ORGANIZATION_DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `RELATION_ORGANIZATION_ALIAS` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_EMAIL` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_MAPPING` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HR_MANAGED_BY_APP` bigint DEFAULT NULL COMMENT '0 = No, 1 = Yes',
  `IS_TBK` bigint DEFAULT NULL,
  `RELATION_ORGANIZATION_LOGO_ID` bigint DEFAULT NULL,
  `RELATION_ORGANIZATION_SIGNATURE_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_SIGNATURE_TITLE` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_BANK_ACCOUNT_NUMBER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_ORGANIZATION_BANK_ACCOUNT_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RELATION_PROFESSION_ID` bigint DEFAULT NULL,
  `RELATION_LOB_ID` bigint DEFAULT NULL,
  `PRE_SALUTATION` bigint DEFAULT NULL,
  `POST_SALUTATION` bigint DEFAULT NULL,
  `relation_status_id` bigint DEFAULT NULL,
  `is_deleted` bigint DEFAULT NULL,
  PRIMARY KEY (`RELATION_ORGANIZATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `t_relation` */

insert  into `t_relation`(`RELATION_ORGANIZATION_ID`,`RELATION_ORGANIZATION_NAME`,`RELATION_ORGANIZATION_PARENT_ID`,`RELATION_ORGANIZATION_ABBREVIATION`,`RELATION_ORGANIZATION_AKA`,`RELATION_ORGANIZATION_GROUP`,`RELATION_ORGANIZATION_CREATED_BY`,`RELATION_ORGANIZATION_CREATED_DATE`,`RELATION_ORGANIZATION_UPDATED_BY`,`RELATION_ORGANIZATION_UPDATED_DATE`,`RELATION_ORGANIZATION_DESCRIPTION`,`RELATION_ORGANIZATION_ALIAS`,`RELATION_ORGANIZATION_EMAIL`,`RELATION_ORGANIZATION_MAPPING`,`HR_MANAGED_BY_APP`,`IS_TBK`,`RELATION_ORGANIZATION_LOGO_ID`,`RELATION_ORGANIZATION_SIGNATURE_NAME`,`RELATION_ORGANIZATION_SIGNATURE_TITLE`,`RELATION_ORGANIZATION_BANK_ACCOUNT_NUMBER`,`RELATION_ORGANIZATION_BANK_ACCOUNT_NAME`,`RELATION_PROFESSION_ID`,`RELATION_LOB_ID`,`PRE_SALUTATION`,`POST_SALUTATION`,`relation_status_id`,`is_deleted`) values (1,'Killian Teknologi Indonesia',0,'KTI',NULL,NULL,'1','2024-07-31 04:33:09',NULL,NULL,NULL,'Killian Teknologi Indonesia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),(2,'Pelabuhan Indonesia',0,'PELINDO',NULL,NULL,'1','2024-07-31 04:33:36',NULL,NULL,NULL,'Pelabuhan Indonesia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),(3,'Sari Enesis Indah',0,'SEI',NULL,NULL,'1','2024-07-31 04:34:05',NULL,NULL,NULL,'Sari Enesis Indah',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
