/*
SQLyog Ultimate v13.1.1 (32 bit)
MySQL - 5.7.12 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `phorcertificatequalification` */

insert  into `r_certificate_qualification`(`CERTIFICATE_QUALIFICATION_ID`,`CERTIFICATE_QUALIFICATION_NAME`,`CERTIFICATE_QUALIFICATION_RENEWAL_BY`,`CERTIFICATE_QUALIFICATION_MAX_POINT`,`CERTIFICATE_QUALIFICATION_LEVEL`) values 
(1,'LEVEL 7 - OJK',2,NULL,6),
(2,'LEVEL 6 - OJK ',2,NULL,5),
(3,'LEVEL 5 - OJK',2,NULL,4),
(4,'CIIB - OJK',1,140,3),
(5,'APAI - OJK',1,120,2),
(6,'AAPAI - OJK',1,80,1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
