/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_expenses` */

DROP TABLE IF EXISTS `t_expenses`;

CREATE TABLE `t_expenses` (
  `EXPENSES_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `EXPENSES_NUMBER` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `EXPENSES_REFF_NUMBER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXPENSES_DIVISION` smallint NOT NULL,
  `EXPENSES_BRANCH` smallint NOT NULL,
  `EXPENSES_REQUESTED_BY` smallint NOT NULL,
  `EXPENSES_REQUESTED_DATE` date NOT NULL,
  `EXPENSES_FIRST_APPROVAL_BY` smallint NOT NULL,
  `EXPENSES_FIRST_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `EXPENSES_FIRST_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `EXPENSES_FIRST_APPROVAL_STATUS` smallint NOT NULL,
  `EXPENSES_FIRST_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `EXPENSES_SECOND_APPROVAL_BY` smallint DEFAULT NULL,
  `EXPENSES_SECOND_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXPENSES_SECOND_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `EXPENSES_SECOND_APPROVAL_STATUS` smallint DEFAULT NULL,
  `EXPENSES_SECOND_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `EXPENSES_REQUEST_NOTE` text COLLATE utf8mb4_unicode_ci,
  `EXPENSES_TYPE` smallint DEFAULT NULL,
  `EXPENSES_METHOD` smallint DEFAULT NULL,
  `EXPENSES_SETTLEMENT_DATE` date DEFAULT NULL,
  `EXPENSES_TOTAL_AMOUNT` decimal(16,2) NOT NULL,
  `EXPENSES_TOTAL_AMOUNT_APPROVE` decimal(16,2) DEFAULT NULL,
  `EXPENSES_TOTAL_AMOUNT_DIFFERENT` decimal(16,2) DEFAULT NULL,
  `EXPENSES_CREATED_AT` datetime DEFAULT NULL,
  `EXPENSES_CREATED_BY` smallint DEFAULT NULL,
  `EXPENSES_UPDATED_AT` datetime DEFAULT NULL,
  `EXPENSES_UPDATED_BY` smallint DEFAULT NULL,
  PRIMARY KEY (`EXPENSES_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
