/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.3.0 : Database - db_phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `m_request_time_off_document` */

DROP TABLE IF EXISTS `m_request_time_off_document`;

CREATE TABLE `m_request_time_off_document` (
  `REQUEST_TIME_OFF_DOCUMENT_ID` int NOT NULL AUTO_INCREMENT,
  `REQUEST_TIME_OFF_MASTER_ID` int DEFAULT NULL,
  `DOCUMENT_ID` int DEFAULT NULL,
  PRIMARY KEY (`REQUEST_TIME_OFF_DOCUMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_collective_leave` */

DROP TABLE IF EXISTS `t_collective_leave`;

CREATE TABLE `t_collective_leave` (
  `COLLECTIVE_LEAVE_ID` int NOT NULL AUTO_INCREMENT,
  `COLLECTIVE_LEAVE_DATE` date DEFAULT NULL,
  PRIMARY KEY (`COLLECTIVE_LEAVE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_request_time_off` */

DROP TABLE IF EXISTS `t_request_time_off`;

CREATE TABLE `t_request_time_off` (
  `REQUEST_TIME_OFF_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `REQUEST_TIME_OFF_MASTER_ID` int DEFAULT NULL,
  `DATE_OF_LEAVE` date DEFAULT NULL,
  PRIMARY KEY (`REQUEST_TIME_OFF_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=512 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_request_time_off_master` */

DROP TABLE IF EXISTS `t_request_time_off_master`;

CREATE TABLE `t_request_time_off_master` (
  `REQUEST_TIME_OFF_MASTER_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `REQUEST_NUMBER` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COLLECTIVE_LEAVE_ID` int DEFAULT NULL COMMENT 'Untuk Cuti Bersama',
  `EMPLOYEE_ID` int DEFAULT NULL,
  `IS_REDUCE_LEAVE` int DEFAULT NULL COMMENT '0:No, 1:Yes',
  `TIME_OFF_TYPE_ID` int DEFAULT NULL,
  `SUBSTITUTE_PIC` int DEFAULT NULL COMMENT 'EMPLOYEE_ID',
  `SECOND_SUBSTITUTE_PIC` int DEFAULT NULL COMMENT 'EMPLOYEE_ID',
  `FILE_ID` int DEFAULT NULL COMMENT 'DOCUMENT_ID',
  `DESCRIPTION` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'DESC REQUEST',
  `REQUEST_DATE` date DEFAULT NULL,
  `REQUEST_TO` int DEFAULT NULL,
  `APPROVED_DATE` datetime DEFAULT NULL,
  `APPROVED_BY` int DEFAULT NULL,
  `STATUS` int DEFAULT NULL COMMENT '0: REQUEST, 1:REJECT, 2:APPROVE',
  `NOTE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'NOTE BY APPROVER',
  `CREATED_BY` int DEFAULT NULL COMMENT 'USER_ID',
  `CREATED_DATE` timestamp NULL DEFAULT NULL,
  `UPDATED_BY` int DEFAULT NULL COMMENT 'USER_ID',
  `UPDATED_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`REQUEST_TIME_OFF_MASTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
