/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_journal_deleted` */

DROP TABLE IF EXISTS `t_journal_deleted`;

CREATE TABLE `t_journal_deleted` (
  `JOURNAL_ID` int unsigned NOT NULL,
  `JOURNAL_NUMBER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOURNAL_TYPE_CODE` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOURNAL_DATE` date DEFAULT NULL,
  `JOURNAL_MEMO` text COLLATE utf8mb4_unicode_ci,
  `JOURNAL_IS_POSTED` smallint DEFAULT NULL,
  `JOURNAL_POSTED_BY` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOURNAL_POSTED_DATE` datetime DEFAULT NULL,
  `JOURNAL_CREATED_BY` int DEFAULT NULL,
  `JOURNAL_CREATED_DATE` datetime DEFAULT NULL,
  `JOURNAL_UPDATED_BY` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOURNAL_UPDATED_DATE` datetime DEFAULT NULL,
  `TEMP` int DEFAULT NULL,
  `JOURNAL_NOTES` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOURNAL_DELETED_BY` int DEFAULT NULL,
  `JOURNAL_DELETED_DATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
