/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.3.0 : Database - db_phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `r_kode_lembur` */

DROP TABLE IF EXISTS `r_kode_lembur`;

CREATE TABLE `r_kode_lembur` (
  `KODE_LEMBUR_ID` int NOT NULL AUTO_INCREMENT,
  `KODE_LEMBUR_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `KETERANGAN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PENGALI_LEMBUR` int DEFAULT NULL COMMENT 'untuk pengali ke nominal lembur',
  PRIMARY KEY (`KODE_LEMBUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `r_kode_lembur` */

insert  into `r_kode_lembur`(`KODE_LEMBUR_ID`,`KODE_LEMBUR_NAME`,`KETERANGAN`,`PENGALI_LEMBUR`) values 
(1,'Hari Biasa',NULL,1),
(2,'Hari Libur',NULL,2),
(3,'Lainnya',NULL,1);

/*Table structure for table `t_additional_allowance` */

DROP TABLE IF EXISTS `t_additional_allowance`;

CREATE TABLE `t_additional_allowance` (
  `ADDITIONAL_ALLOWANCE_ID` int NOT NULL AUTO_INCREMENT,
  `ADDITIONAL_ALLOWANCE_NAME` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_AMOUNT` decimal(20,2) DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_UANG_MAKAN` decimal(20,2) DEFAULT '0.00',
  `ADDITIONAL_ALLOWANCE_CREATED_BY` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_CREATED_DATE` datetime DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_UPDATED_BY` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_UPDATED_DATE` datetime DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_NOTE` varchar(256) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`ADDITIONAL_ALLOWANCE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `t_additional_allowance` */

insert  into `t_additional_allowance`(`ADDITIONAL_ALLOWANCE_ID`,`ADDITIONAL_ALLOWANCE_NAME`,`ADDITIONAL_ALLOWANCE_AMOUNT`,`ADDITIONAL_ALLOWANCE_UANG_MAKAN`,`ADDITIONAL_ALLOWANCE_CREATED_BY`,`ADDITIONAL_ALLOWANCE_CREATED_DATE`,`ADDITIONAL_ALLOWANCE_UPDATED_BY`,`ADDITIONAL_ALLOWANCE_UPDATED_DATE`,`ADDITIONAL_ALLOWANCE_NOTE`) values 
(1,'Lembur',10000.00,25000.00,'fitano','2023-06-12 04:44:53','fitano','2023-07-04 05:52:42','Per-Hour'),
(3,'Perjalanan Luar Kota',100000.00,0.00,'fitano','2023-06-14 02:05:20','fitano','2023-06-15 02:30:26','Per Day');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
