/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.2.0 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_person` */

DROP TABLE IF EXISTS `t_person`;

CREATE TABLE `t_person` (
  `PERSON_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `PERSONE_ID` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_FIRST_NAME` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_MIDDLE_NAME` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_LAST_NAME` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_NICKNAME` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_GENDER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'm = male, f = female',
  `PERSON_BIRTH_PLACE` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BIRTH_DATE` date DEFAULT NULL,
  `PERSON_EMAIL` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_CONTACT` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INDIVIDU_RELATION_ID` bigint DEFAULT NULL,
  `PERSON_CREATED_BY` bigint DEFAULT NULL,
  `PERSON_CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PERSON_UPDATED_BY` bigint DEFAULT NULL,
  `PERSON_UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PERSON_KTP` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_NPWP` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BANK_ACCOUNT_ID` int DEFAULT NULL,
  `PERSON_IMAGE_ID` int DEFAULT NULL,
  `PERSON_KK` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PERSON_BLOOD_TYPE` int DEFAULT NULL COMMENT '1=A, 2=B, 3=AB, 4=0',
  `PERSON_BLOOD_RHESUS` int DEFAULT NULL COMMENT '1=positive, 2=negative',
  `PERSON_MARITAL_STATUS` int DEFAULT NULL COMMENT '1=Single, 2= Married,3=Divorced,4=Widowed',
  `PERSON_LOCK_UPDATE` int DEFAULT NULL COMMENT 'null/0 = lock 1=unlock',
  `PERSON_LOCK_UPDATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`PERSON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_person_contact` */

DROP TABLE IF EXISTS `t_person_contact`;

CREATE TABLE `t_person_contact` (
  `PERSON_CONTACT_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` bigint DEFAULT NULL,
  `PERSON_PHONE_NUMBER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`PERSON_CONTACT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_person_email` */

DROP TABLE IF EXISTS `t_person_email`;

CREATE TABLE `t_person_email` (
  `PERSON_EMAIL_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` bigint DEFAULT NULL,
  `PERSON_EMAIL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`PERSON_EMAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_pic` */

DROP TABLE IF EXISTS `t_pic`;

CREATE TABLE `t_pic` (
  `PIC_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` bigint DEFAULT NULL,
  `RELATION_ORGANIZATION_ID` bigint DEFAULT NULL,
  `PIC_IS_VIP` smallint DEFAULT '0' COMMENT '0 = Non VIP, 1 = VIP',
  `DIVISION_ID` bigint DEFAULT NULL,
  `STRUCTURE_ID` bigint DEFAULT NULL,
  `OFFICE_ID` bigint DEFAULT NULL,
  `PIC_IS_DELETED` smallint DEFAULT '0' COMMENT '0 = Active, 1 = inActice',
  `PIC_CREATED_BY` smallint DEFAULT NULL,
  `PIC_CREATED_DATE` datetime DEFAULT NULL,
  `PIC_UPDATED_BY` smallint DEFAULT NULL,
  `PIC_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`PIC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
