/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 5.7.36 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_chat_detail_user` */

DROP TABLE IF EXISTS `t_chat_detail_user`;

CREATE TABLE `t_chat_detail_user` (
  `CHAT_DETAIL_USER_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `CHAT_ID` bigint(20) DEFAULT NULL,
  `CHAT_DETAIL_ID` bigint(20) DEFAULT NULL,
  `CHAT_DETAIL_USER_FROM` bigint(20) DEFAULT NULL,
  `CHAT_DETAIL_USER_TO` bigint(20) DEFAULT NULL,
  `CHAT_DETAIL_USER_STATUS_READ` bigint(20) DEFAULT NULL COMMENT '0 = unread, 1 = read',
  `CHAT_DETAIL_USER_READ_DATE` datetime DEFAULT NULL,
  `CHAT_DETAIL_USER_STATUS_MENTION` bigint(20) DEFAULT NULL COMMENT '0 = tidak di mention, 1 = mention',
  `CHAT_DETAIL_USER_REPLY_DATE` datetime DEFAULT NULL,
  `CHAT_DETAIL_USER_RELATE_CHAT_DETAIL_ID` bigint(20) DEFAULT NULL,
  `CHAT_DETAIL_USER_CREATED_DATE` datetime DEFAULT NULL,
  `CHAT_DETAIL_USER_CREATED_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CHAT_DETAIL_USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=446 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
