/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.3.0 : Database - db_phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `m_lembur_detail` */

DROP TABLE IF EXISTS `m_lembur_detail`;

CREATE TABLE `m_lembur_detail` (
  `LEMBUR_DETAIL_ID` int NOT NULL AUTO_INCREMENT,
  `LEMBUR_ID` int DEFAULT NULL,
  `ADDITIONAL_ALLOWANCE_ID` int DEFAULT NULL,
  `LEMBUR_DATE` date DEFAULT NULL,
  `KODE_LEMBUR` int DEFAULT NULL,
  `LEMBUR_IN` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LEMBUR_OUT` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JUMLAH_JAM_LEMBUR` int DEFAULT NULL,
  `TOTAL_UANG_LEMBUR` decimal(20,2) DEFAULT NULL,
  `SHIFT_ID` int DEFAULT NULL COMMENT 'ATTENDANCE_SETTING_ID yg tipe nya SHIFT',
  `UANG_MAKAN` decimal(20,2) DEFAULT NULL,
  `LEMBUR_UANG_MAKAN` decimal(20,2) DEFAULT NULL,
  PRIMARY KEY (`LEMBUR_DETAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_lembur` */

DROP TABLE IF EXISTS `t_lembur`;

CREATE TABLE `t_lembur` (
  `LEMBUR_ID` int NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int DEFAULT NULL,
  `TANGGAL` date DEFAULT NULL,
  `TANGGAL_PERIODE` date DEFAULT NULL,
  `TANGGAL_PERIODE_2` date DEFAULT NULL,
  `PERIODE_PENGGAJIAN` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPTION` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` int DEFAULT NULL,
  `COMPANY_ID` int DEFAULT NULL,
  PRIMARY KEY (`LEMBUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
