ALTER TABLE `db_phoenix`.`t_request_time_off_master`
  ADD COLUMN `IS_CANCELED` TINYINT DEFAULT 0 NULL COMMENT '0: NO, 1: YES (Cancel By Requester)' AFTER `UPDATED_DATE`,
  ADD COLUMN `CANCELED_DATE` TIMESTAMP NULL AFTER `IS_CANCELED`,
  ADD COLUMN `CANCELED_BY` INT NULL AFTER `CANCELED_DATE`;
