/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.3.0 : Database - db_phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `m_medical_detail` */

DROP TABLE IF EXISTS `m_medical_detail`;

CREATE TABLE `m_medical_detail` (
  `MEDICAL_DETAIL_ID` int NOT NULL AUTO_INCREMENT,
  `MEDICAL_ID` int DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `DESCRIPTION` text CHARACTER SET latin1,
  `NOTE_APPROVAL` text CHARACTER SET latin1 COMMENT 'catatan dari approver',
  PRIMARY KEY (`MEDICAL_DETAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `m_medical_document` */

DROP TABLE IF EXISTS `m_medical_document`;

CREATE TABLE `m_medical_document` (
  `MEDICAL_DOCUMENT_ID` int NOT NULL AUTO_INCREMENT,
  `MEDICAL_ID` int DEFAULT NULL,
  `DOCUMENT_ID` int DEFAULT NULL,
  PRIMARY KEY (`MEDICAL_DOCUMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `t_medical` */

DROP TABLE IF EXISTS `t_medical`;

CREATE TABLE `t_medical` (
  `MEDICAL_ID` int NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int DEFAULT NULL,
  `COMPANY_ID` int DEFAULT NULL,
  `DIVISION_ID` int DEFAULT NULL,
  `STRUCTURE_ID` int DEFAULT NULL,
  `MEDICAL_TYPE` int DEFAULT NULL COMMENT '1:General; 2:Maternity',
  `MEDICAL_AMOUNT` decimal(20,2) DEFAULT NULL,
  `MEDICAL_LIMIT` decimal(20,2) DEFAULT NULL,
  `REQUEST_DATE` date DEFAULT NULL,
  `STATUS` int DEFAULT NULL COMMENT 'null:request; 0:Reject; 1:Approved',
  `APPROVE_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MEDICAL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
