/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `r_journal_setting_detail` */

insert  into `r_journal_setting_detail`(`JOURNAL_SETTING_DETAIL_ID`,`JOURNAL_SETTING_ID`,`JOURNAL_SETTING_DETAIL_TITLE`,`JOURNAL_SETTING_DETAIL_COA`,`JOURNAL_SETTING_DETAIL_SIDE`,`JOURNAL_SETTING_DETAIL_CREATED_BY`,`JOURNAL_SETTING_DETAIL_CREATED_DATE`,`JOURNAL_SETTING_DETAIL_UPDATED_BY`,`JOURNAL_SETTING_DETAIL_UPDATED_DATE`) values (1,1,'PRJ Bank',NULL,1,1,'2024-11-21 13:55:29',NULL,NULL),(2,1,'Hutang Lainnya',21370,2,1,'2024-11-21 13:55:32',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
