ALTER TABLE `db_phoenix`.`t_collective_leave`
  DROP COLUMN `COLLECTIVE_LEAVE_DATE`,
  ADD COLUMN `STATUS` TINYINT DEFAULT 1 NULL COMMENT '0:Reject/Cancel, 1:Approve' AFTER `COLLECTIVE_LEAVE_ID`,
  ADD COLUMN `TITLE` VARCHAR (255) NULL AFTER `STATUS`;
  ADD COLUMN `CREATED_BY` INT NULL AFTER `TITLE`,
  ADD COLUMN `CREATED_DATE` TIMESTAMP NULL AFTER `CREATED_BY`;
