/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 5.7.36 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_reminder` */

DROP TABLE IF EXISTS `t_reminder`;

CREATE TABLE `t_reminder` (
  `REMINDER_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `REMINDER_TITLE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REMINDER_TIMES` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REMINDER_DAYS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REMINDER_START_DATE` date DEFAULT NULL,
  `REMINDER_STATUS` smallint(6) DEFAULT '0' COMMENT '0 = Active, 1 = Inactive',
  `REMINDER_DESKRIPSI` text COLLATE utf8mb4_unicode_ci,
  `REMINDER_CREATED_BY` bigint(20) DEFAULT NULL,
  `REMINDER_CREATED_DATE` datetime DEFAULT NULL,
  `REMINDER_UPDATED_BY` bigint(20) DEFAULT NULL,
  `REMINDER_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`REMINDER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
