/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_expenses_detail` */

DROP TABLE IF EXISTS `t_expenses_detail`;

CREATE TABLE `t_expenses_detail` (
  `EXPENSES_DETAIL_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `EXPENSES_ID` smallint NOT NULL,
  `EXPENSES_DETAIL_DUE_DATE` date NOT NULL,
  `EXPENSES_DETAIL_TYPE` smallint NOT NULL,
  `EXPENSES_DETAIL_CURRENCY` smallint NOT NULL,
  `EXPENSES_DETAIL_AMOUNT_VALUE` decimal(16,2) NOT NULL,
  `EXPENSES_DETAIL_RELATION_ORGANIZATION_ID` smallint NOT NULL,
  `EXPENSES_DETAIL_DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `EXPENSES_DETAIL_APPROVAL` smallint NOT NULL,
  `EXPENSES_DETAIL_COST_CLASSIFICATION` smallint NOT NULL,
  `EXPENSES_DETAIL_AMOUNT_VALUE_APPROVE` decimal(16,2) NOT NULL,
  `EXPENSES_DETAIL_REMARKS` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`EXPENSES_DETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
