CREATE TABLE `db_phoenix`.`t_collective_leave_detail` (
  `COLLECTIVE_LEAVE_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
  `COLLECTIVE_LEAVE_ID` INT,
  `COLLECTIVE_LEAVE_DETAIL_DATE` DATE,
  PRIMARY KEY (`COLLECTIVE_LEAVE_DETAIL_ID`)
);