/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_journal_detail_deleted` */

DROP TABLE IF EXISTS `t_journal_detail_deleted`;

CREATE TABLE `t_journal_detail_deleted` (
  `JOURNAL_DETAIL_ID` int unsigned NOT NULL,
  `JOURNAL_ID` bigint NOT NULL,
  `JOURNAL_DETAIL_COA_CODE` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOURNAL_DETAIL_DESC` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOURNAL_DETAIL_CURRENCY_ID` smallint NOT NULL,
  `JOURNAL_DETAIL_ORIG` decimal(18,2) NOT NULL,
  `JOURNAL_DETAIL_EX_RATE` decimal(10,2) NOT NULL,
  `JOURNAL_DETAIL_SUM` decimal(18,2) NOT NULL,
  `JOURNAL_DETAIL_SIDE` smallint NOT NULL,
  `JOURNAL_DETAIL_CREATED_BY` int DEFAULT NULL,
  `JOURNAL_DETAIL_CREATED_DATE` datetime DEFAULT NULL,
  `JOURNAL_DETAIL_UPDATED_BY` int DEFAULT NULL,
  `JOURNAL_DETAIL_UPDATED_DATE` datetime DEFAULT NULL,
  `JOURNAL_DETAIL_DELETED_BY` int DEFAULT NULL,
  `JOURNAL_DETAIL_DELETED_DATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
