/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_receipt` */

DROP TABLE IF EXISTS `t_receipt`;

CREATE TABLE `t_receipt` (
  `RECEIPT_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `RECEIPT_DOCUMENT_ID` int DEFAULT NULL,
  `RECEIPT_CURRENCY_ID` smallint DEFAULT NULL,
  `RECEIPT_BANK_ID` smallint DEFAULT NULL,
  `RECEIPT_JOURNAL_ID` bigint DEFAULT NULL,
  `RECEIPT_JOURNAL_ID_ADD_RECEIPT` bigint DEFAULT NULL,
  `RECEIPT_RELATION_ORGANIZATION_ID` int DEFAULT NULL,
  `RECEIPT_NUMBER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIPT_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIPT_DATE` date DEFAULT NULL,
  `RECEIPT_VALUE` decimal(16,2) DEFAULT NULL,
  `RECEIPT_COUNTED_AS` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIPT_EXCHANGE_RATE` decimal(16,2) DEFAULT NULL,
  `RECEIPT_MEMO` text COLLATE utf8mb4_unicode_ci,
  `RECEIPT_STATUS` tinyint DEFAULT NULL,
  `RECEIPT_CREATED_BY` int DEFAULT NULL,
  `RECEIPT_CREATED_AT` datetime DEFAULT NULL,
  `RECEIPT_UPDATED_BY` int DEFAULT NULL,
  `RECEIPT_UPDATED_AT` datetime DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`RECEIPT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
