/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`phoenix` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

/*Table structure for table `r_journal_setting` */

DROP TABLE IF EXISTS `r_journal_setting`;

CREATE TABLE `r_journal_setting` (
  `JOURNAL_SETTING_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `JOURNAL_SETTING_CODE` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOURNAL_SETTING_TITLE` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOURNAL_SETTING_TYPE` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOURNAL_SETTING_AUTOMATIC_SETTING` tinyint NOT NULL DEFAULT '0',
  `JOURNAL_SETTING_CREATED_BY` int DEFAULT NULL,
  `JOURNAL_SETTING_CREATED_DATE` datetime DEFAULT NULL,
  `JOURNAL_SETTING_UPDATED_BY` int DEFAULT NULL,
  `JOURNAL_SETTING_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`JOURNAL_SETTING_ID`),
  UNIQUE KEY `r_journal_setting_journal_setting_code_unique` (`JOURNAL_SETTING_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
