/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_report_cash_advance` */

DROP TABLE IF EXISTS `t_report_cash_advance`;

CREATE TABLE `t_report_cash_advance` (
  `REPORT_CASH_ADVANCE_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `REPORT_CASH_ADVANCE_CASH_ADVANCE_ID` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_NUMBER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REPORT_CASH_ADVANCE_DIVISION` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REPORT_CASH_ADVANCE_COST_CENTER` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_BRANCH` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_USED_BY` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_REQUESTED_BY` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_REQUESTED_DATE` datetime NOT NULL,
  `REPORT_CASH_ADVANCE_FIRST_APPROVAL_BY` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_FIRST_APPROVAL_USER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REPORT_CASH_ADVANCE_FIRST_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REPORT_CASH_ADVANCE_FIRST_APPROVAL_STATUS` smallint NOT NULL,
  `REPORT_CASH_ADVANCE_FIRST_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REPORT_CASH_ADVANCE_SECOND_APPROVAL_BY` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_SECOND_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPORT_CASH_ADVANCE_SECOND_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REPORT_CASH_ADVANCE_SECOND_APPROVAL_STATUS` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_SECOND_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REPORT_CASH_ADVANCE_THIRD_APPROVAL_BY` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_THIRD_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPORT_CASH_ADVANCE_THIRD_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REPORT_CASH_ADVANCE_THIRD_APPROVAL_STATUS` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_THIRD_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REPORT_CASH_ADVANCE_REQUEST_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REPORT_CASH_ADVANCE_TYPE` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_AMOUNT` decimal(16,2) DEFAULT NULL,
  `REPORT_CASH_ADVANCE_METHOD` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_PROOF_OF_DOCUMENT` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPORT_CASH_ADVANCE_TRANSACTION_DATE` date DEFAULT NULL,
  `REPORT_CASH_ADVANCE_TOTAL_AMOUNT` decimal(16,2) DEFAULT NULL,
  `REPORT_CASH_ADVANCE_TOTAL_AMOUNT_REQUEST` decimal(16,2) DEFAULT NULL,
  `REPORT_CASH_ADVANCE_TOTAL_AMOUNT_APPROVE` decimal(16,2) DEFAULT NULL,
  `REPORT_CASH_ADVANCE_TOTAL_AMOUNT_DIFFERENT` decimal(16,2) DEFAULT NULL,
  `REPORT_CASH_ADVANCE_CREATED_BY` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_CREATED_DATE` datetime DEFAULT NULL,
  `REPORT_CASH_ADVANCE_UPDATED_BY` smallint DEFAULT NULL,
  `REPORT_CASH_ADVANCE_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`REPORT_CASH_ADVANCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
