/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_reimburse` */

DROP TABLE IF EXISTS `t_reimburse`;

CREATE TABLE `t_reimburse` (
  `REIMBURSE_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `REIMBURSE_NUMBER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_DIVISION` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_COST_CENTER` smallint DEFAULT NULL,
  `REIMBURSE_BRANCH` smallint DEFAULT NULL,
  `REIMBURSE_USED_BY` smallint NOT NULL,
  `REIMBURSE_REQUESTED_BY` smallint NOT NULL,
  `REIMBURSE_REQUESTED_DATE` datetime DEFAULT NULL,
  `REIMBURSE_FIRST_APPROVAL_BY` smallint NOT NULL,
  `REIMBURSE_FIRST_APPROVAL_USER` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_FIRST_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REIMBURSE_FIRST_APPROVAL_STATUS` smallint NOT NULL,
  `REIMBURSE_FIRST_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REIMBURSE_SECOND_APPROVAL_BY` smallint DEFAULT NULL,
  `REIMBURSE_SECOND_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REIMBURSE_SECOND_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REIMBURSE_SECOND_APPROVAL_STATUS` smallint DEFAULT NULL,
  `REIMBURSE_SECOND_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REIMBURSE_THIRD_APPROVAL_BY` smallint DEFAULT NULL,
  `REIMBURSE_THIRD_APPROVAL_USER` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REIMBURSE_THIRD_APPROVAL_CHANGE_STATUS_DATE` datetime DEFAULT NULL,
  `REIMBURSE_THIRD_APPROVAL_STATUS` smallint DEFAULT NULL,
  `REIMBURSE_THIRD_APPROVAL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REIMBURSE_REQUEST_NOTE` text COLLATE utf8mb4_unicode_ci,
  `REIMBURSE_TYPE` smallint DEFAULT NULL,
  `REIMBURSE_METHOD` smallint DEFAULT NULL,
  `REIMBURSE_SETTLEMENT_DATE` date DEFAULT NULL,
  `REIMBURSE_TOTAL_AMOUNT` decimal(16,2) DEFAULT NULL,
  `REIMBURSE_TOTAL_AMOUNT_APPROVE` decimal(16,2) DEFAULT NULL,
  `REIMBURSE_TOTAL_AMOUNT_DIFFERENT` decimal(16,2) DEFAULT NULL,
  `REIMBURSE_CREATED_BY` smallint DEFAULT NULL,
  `REIMBURSE_CREATED_DATE` datetime DEFAULT NULL,
  `REIMBURSE_UPDATED_BY` smallint DEFAULT NULL,
  `REIMBURSE_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`REIMBURSE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
