/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_reimburse_detail` */

DROP TABLE IF EXISTS `t_reimburse_detail`;

CREATE TABLE `t_reimburse_detail` (
  `REIMBURSE_DETAIL_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `REIMBURSE_ID` smallint DEFAULT NULL,
  `REIMBURSE_DETAIL_DATE` date NOT NULL,
  `REIMBURSE_DETAIL_PURPOSE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_DETAIL_LOCATION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_DETAIL_ADDRESS` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `REIMBURSE_DETAIL_TYPE` smallint NOT NULL,
  `REIMBURSE_DETAIL_RELATION_ORGANIZATION_ID` smallint DEFAULT NULL,
  `REIMBURSE_DETAIL_RELATION_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REIMBURSE_DETAIL_RELATION_POSITION` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REIMBURSE_DETAIL_AMOUNT` decimal(16,2) NOT NULL,
  `REIMBURSE_DETAIL_APPROVAL` smallint DEFAULT NULL,
  `REIMBURSE_DETAIL_COST_CLASSIFICATION` smallint DEFAULT NULL,
  `REIMBURSE_DETAIL_AMOUNT_APPROVE` decimal(16,2) DEFAULT NULL,
  `REIMBURSE_DETAIL_REMARKS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`REIMBURSE_DETAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
