/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 10.4.32-MariaDB : Database - phoenixfixed
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `r_milestone` */

DROP TABLE IF EXISTS `r_milestone`;

CREATE TABLE `r_milestone` (
  `MILESTONE_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `MILESTONE_NAME` varchar(191) DEFAULT NULL,
  `MILESTONE_PARENT_ID` int(11) DEFAULT NULL,
  `WORKBOOK_ID` int(11) DEFAULT NULL,
  `DURATION_TYPE_ID` int(11) DEFAULT NULL,
  `MILESTONE_DURATION_MIN` int(11) DEFAULT NULL,
  `MILESTONE_DURATION_MAX` int(11) DEFAULT NULL,
  `MILESTONE_DURATION_DESCRIPTION` varchar(191) DEFAULT NULL,
  `MILESTONE_MAPPING` varchar(191) DEFAULT NULL,
  `MILESTONE_SEQUENCE` int(11) DEFAULT NULL,
  `MILESTONE_IS_DELETED` int(11) DEFAULT 0,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MILESTONE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=637 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
