/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_exchange_rate_tax_detail` */

DROP TABLE IF EXISTS `t_exchange_rate_tax_detail`;

CREATE TABLE `t_exchange_rate_tax_detail` (
  `EXCHANGE_RATE_TAX_DETAIL_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `EXCHANGE_RATE_TAX_ID` bigint NOT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_CURRENCY_ID` smallint NOT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_EXCHANGE_RATE` decimal(16,2) NOT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_CREATED_BY` smallint NOT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_CREATED_AT` datetime NOT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_UPDATED_BY` smallint DEFAULT NULL,
  `EXCHANGE_RATE_TAX_DETAIL_UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`EXCHANGE_RATE_TAX_DETAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
