/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 8.0.31 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_cash_advance_detail` */

DROP TABLE IF EXISTS `t_cash_advance_detail`;

CREATE TABLE `t_cash_advance_detail` (
  `CASH_ADVANCE_DETAIL_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `CASH_ADVANCE_ID` smallint NOT NULL,
  `CASH_ADVANCE_DETAIL_START_DATE` date NOT NULL,
  `CASH_ADVANCE_DETAIL_END_DATE` date NOT NULL,
  `CASH_ADVANCE_DETAIL_PURPOSE` smallint NOT NULL,
  `CASH_ADVANCE_DETAIL_LOCATION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CASH_ADVANCE_DETAIL_RELATION_ORGANIZATION_ID` smallint DEFAULT NULL,
  `CASH_ADVANCE_DETAIL_RELATION_NAME` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CASH_ADVANCE_DETAIL_RELATION_POSITION` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CASH_ADVANCE_DETAIL_AMOUNT` decimal(16,2) NOT NULL,
  `CASH_ADVANCE_DETAIL_STATUS` tinyint(1) DEFAULT NULL,
  `CASH_ADVANCE_DETAIL_DOCUMENT_ID` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CASH_ADVANCE_DETAIL_NOTE` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`CASH_ADVANCE_DETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
