/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 5.7.36 : Database - phoenix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_employee_family_member` */

DROP TABLE IF EXISTS `t_employee_family_member`;

CREATE TABLE `t_employee_family_member` (
  `EMPLOYEE_FAMILY_MEMBER_ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` bigint(11) DEFAULT NULL,
  `EMPLOYEE_FAMILY_MEMBER_NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMPLOYEE_RELATIONSHIP_ID` bigint(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_FAMILY_MEMBER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
